### ISSUE TITLE
Failed to insert the rule

### ISSUE THREAD

**Issue by eugene-ilyin** [sampotts/rangetouch#14]
I've faced with a problem.
When the user opens the page on a mobile device or even in Google Chrome in a mobile device mode (I've used option iPad Pro), there is an error:

`rangetouch.js:54 Uncaught DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to insert the rule.`

The exact rule is 
`[type="range"]:not(.rangetouch--disabled) { user-select: none; -webkit-user-select: none; touch-action: manipulation; }`
I don't see anything wrong in this rule.

I've investigated this guide https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule, but there is nothing about this problem. I've tried to replace index 0 on stylesheet.cssRules.length and it helped. Not clear why exactly is it but it works.
If somebody can explain the problem in a better way, you're welcome!

Finally, the updated line looks like:
`stylesheet.insertRule(getSelector() + ' { user-select: none; -webkit-user-select: none; touch-action: manipulation; }', stylesheet.cssRules.length);`

**Comment by ptmt** [comment]
It seems that this PR https://github.com/sampotts/rangetouch/pull/13 fixes this, @sampotts any reason you didn't publish the updated version to npm?

**Comment by sampotts** [comment]
Sorry, I'll get this done. Family + Work + Plyr sucks up all of my time.

**Comment by sampotts** [comment]
All published to `v1.0.6` in npm.
