### ISSUE TITLE
Why I need to dispatch the event change / input of input[type=range] here?

### ISSUE THREAD

**Issue by TomIsion** [sampotts/rangetouch#2]
First of all, this `rangetouch` is cool.

But when I read your source code, I feel confused on this statement:

```
// Trigger input event
_triggerEvent(event.target, (event.type === settings.events.end ? 'change' : 'input'));
```

As my issue title says, I don't know why you dispatch events: `change` / `input`?

Maybe these means different to `input[type=range]`?

**Comment by SamPotts** [comment]
Thanks 👍 

It's been a while since I've worked on it but from memory, this is to mimmic the standard event behaviour but for touch - i.e. an `input` event is fired on every value change and then once dragging is complete then the `change` event is fired.
