### ISSUE TITLE
Thoughts on using with React/Redux

### ISSUE THREAD

**Issue by pedalpete** [sampotts/rangetouch#7]
After building some nice slider interactions with React, I find that it doesn't work on iOS. 

I tried importing rangetouch from the CDN into my project, but it didn't seem to have the desired effect. 

Any suggestions on working with rangetouch and shadowdom?

**Comment by donysukardi** [comment]
After https://github.com/sampotts/rangetouch/pull/20 gets merged, it should be as straightforward as the following,
```
function RangeInput(props) {
  const inputRef = React.useRef(null);
  React.useEffect(() => {
    new RangeTouch(inputRef.current);
  }, []);

  return (
    <input
      ref={inputRef}
      type="range"
      {...props}
    />
  );
}
```
